name       : xtitle
version    : 0.3
release    : 1
source     :
    - https://github.com/baskerville/xtitle/archive/0.3.tar.gz : 817af5b7e6014d24840404722c2b6a44c44a7b226dfad1e76d0087a68833231f
license    : Public-Domain
component  : system.utils
summary    : Outputs X window titles
description: |
    Outputs X window titles
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
