name       : xtitle
version    : 0.4.4
release    : 3
source     :
    - https://github.com/baskerville/xtitle/archive/0.4.4.tar.gz : c2fbf403892c4e466e43528415284a458d4354855f221273881aa4388d028970
license    : Public-Domain
component  : system.utils
summary    : Outputs X window titles
description: |
    Outputs X window titles
builddeps  :
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
